export { createUpdateClient } from './createUpdateClient';
export { androidDebug } from './androidDebug';
export { sources } from './sources';
export { CheckResult } from './types';

export type {
  AppStoreRetryConfig,
  AndroidFakeInstallErrorCode,
  AndroidFakePlayStoreAction,
  AndroidFakePlayStoreAllowedUpdateType,
  AndroidFakePlayStoreAvailability,
  AndroidFakePlayStoreConfig,
  AndroidFakePlayStoreController,
  AndroidFakePlayStoreDebugResult,
  AndroidFakePlayStoreState,
  AndroidFakePlayStoreStateAvailability,
  AndroidPlatformConfig,
  AndroidSourceConfig,
  AppStoreSourceConfig,
  CheckErrorType,
  CheckForUpdateOptions,
  CheckMode,
  CheckStatus,
  CustomSourceConfig,
  CustomUpdateProvider,
  CustomUpdateProviderContext,
  CustomUpdateProviderResult,
  FailedUpdateResult,
  FakePlayStoreSourceConfig,
  ILogger,
  IOSPlatformConfig,
  IOSSourceConfig,
  PerformUpdateFailureReason,
  PerformUpdateResult,
  PlatformName,
  PlayStoreFlow,
  PlayStoreSourceConfig,
  RedirectedUpdateResult,
  ReservedAppConfig,
  SourceType,
  StartedUpdateResult,
  UpdateClient,
  UpdateClientConfig,
  UpdateClientDebuggingConfig,
  UpdateMetadata,
} from './types';
