name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Typecheck files
        run: yarn typecheck

      - name: Build package
        run: yarn prepare

  publish:
    needs: test
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: refs/tags/${{ github.event.release.tag_name }}

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build package
        run: yarn prepare

      - name: Publish to npm
        run: npm publish --provenance --access public
